# command: conda env create -f environment.yml
name: NoBox
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.12=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2020.0=166
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py37he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.2=he6710b0_0
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - openssl=1.0.2u=h7b6447c_0
  - pcre=8.43=he6710b0_0
  - pillow=6.1.0=py37h34e0f95_0
  - pip=20.0.2=py37_1
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.0=h6e4f718_3
  - python-dateutil=2.8.1=py_0
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - qt=5.9.6=h8703b6f_2
  - readline=7.0=h7b6447c_5
  - setuptools=46.1.3=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.5.0=py37_cu101
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.43.0=py_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - advertorch==0.2.2
    - astor==0.8.1
    - backcall==0.1.0
    - chardet==3.0.4
    - click==7.1.1
    - configparser==5.0.0
    - decorator==4.4.2
    - docker-pycreds==0.4.0
    - gast==0.2.2
    - gitdb==4.0.4
    - gitpython==3.1.1
    - google-pasta==0.2.0
    - gql==0.2.0
    - graphql-core==1.1
    - grpcio==1.28.1
    - h5py==2.10.0
    - idna==2.9
    - ipdb==0.13.2
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - jedi==0.16.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.2.1
    - nvidia-ml-py3==7.352.0
    - opt-einsum==3.2.0
    - parso==0.7.0
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - promise==2.3
    - prompt-toolkit==3.0.5
    - protobuf==3.11.3
    - psutil==5.7.0
    - ptyprocess==0.6.0
    - pygments==2.6.1
    - pyyaml==5.3.1
    - requests==2.23.0
    - sentry-sdk==0.14.3
    - shortuuid==1.0.1
    - smmap==3.0.2
    - subprocess32==3.5.4
    - tensorboard==1.15.0
    - tensorflow-estimator==1.15.1
    - tensorflow-gpu==1.15.0
    - termcolor==1.1.0
    - traitlets==4.3.3
    - urllib3==1.25.9
    - wandb==0.8.32
    - watchdog==0.10.2
    - wcwidth==0.1.9
    - werkzeug==1.0.1
    - wrapt==1.12.1

